apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-blue
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-blue
    spec:
      containers:
      - name: node-blue
        image: chen23/f5-demo-app:openshift
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "Node Blue (No SSL)"
        - name: F5DEMO_NODENAME_SSL
          value: "Node Blue (SSL)"
        - name: F5DEMO_COLOR
          value: "0000FF"
        - name: F5DEMO_COLOR_SSL
          value: "0000FF"
        ports:
         - containerPort: 8080
           protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-blue
  labels:
    name: node-blue
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-blue
